export const assetManifest = [
  {
    id: "aster-house-card-v2",
    project: "Aster House",
    path: "/images/generated/aster-house-card-v2.png",
    sourceUrl: "Generated with OpenAI ImageGen",
    creator: "OpenAI ImageGen for NIVĀRA",
    license: "Project-generated conceptual asset",
    focalPoint: "50% 52%",
    alt: "Conceptual limestone and glass residence beneath mature woodland trees",
    replacementStatus: "Concept image — do not represent as a completed property",
  },
  {
    id: "nivara-hero",
    project: "Aster House",
    path: "/images/generated/nivara-hero.png",
    sourceUrl: "Generated with OpenAI ImageGen",
    creator: "OpenAI ImageGen for NIVĀRA",
    license: "Project-generated conceptual asset",
    focalPoint: "58% 50%",
    alt: "Conceptual warm modern residential building with planted curved balconies at sunset",
    replacementStatus: "Concept image — do not represent as a completed property",
  },
  {
    id: "casa-neru",
    project: "Casa Neru",
    path: "/images/generated/casa-neru.png",
    sourceUrl: "Generated with OpenAI ImageGen",
    creator: "OpenAI ImageGen for NIVĀRA",
    license: "Project-generated conceptual asset",
    focalPoint: "50% 56%",
    alt: "Conceptual lime-plaster Goa villa opening onto a reflective courtyard pool",
    replacementStatus: "Concept image — do not represent as a completed property",
  },
  {
    id: "stock-courtyard",
    project: "Courtyard 07",
    path: "https://images.unsplash.com/photo-1600585154340-be6161a56a0c",
    sourceUrl: "https://images.unsplash.com/photo-1600585154340-be6161a56a0c",
    creator: "Unsplash contributor",
    license: "Unsplash License — verify credit before launch",
    focalPoint: "50% 50%",
    alt: "Contemporary house with dark framing and lush surrounding trees",
    replacementStatus: "Illustrative stock — replace with owned project photography",
  },
  {
    id: "stock-mountain",
    project: "Hima House",
    path: "https://images.unsplash.com/photo-1600607687939-ce8a6c25118c",
    sourceUrl: "https://images.unsplash.com/photo-1600607687939-ce8a6c25118c",
    creator: "Unsplash contributor",
    license: "Unsplash License — verify credit before launch",
    focalPoint: "50% 50%",
    alt: "Modern timber and glass house viewed in soft mountain light",
    replacementStatus: "Illustrative stock — replace with owned project photography",
  },
] as const;
